# Generated by Django 5.1.7 on 2025-03-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="topic",
        ),
        migrations.AddField(
            model_name="word",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
