# Generated by Django 5.1.7 on 2025-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_remove_word_topic_word_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={},
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="description",
            new_name="definition",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="name",
            new_name="word",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="user",
        ),
        migrations.AddField(
            model_name="topic",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="topics",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="definition",
            field=models.TextField(blank=True),
        ),
    ]
