# Generated by Django 5.1.7 on 2025-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="word",
            options={},
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="word",
            new_name="wordt",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="topics",
        ),
        migrations.AddField(
            model_name="topic",
            name="name",
            field=models.CharField(default="Default Topic", max_length=100),
        ),
        migrations.AddField(
            model_name="word",
            name="name",
            field=models.CharField(default="Default Topic", max_length=100),
        ),
    ]
