# Generated by Django 5.1.7 on 2025-03-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_alter_topic_options_alter_word_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["wordt"]},
        ),
        migrations.RemoveField(
            model_name="topic",
            name="name",
        ),
        migrations.RemoveField(
            model_name="word",
            name="name",
        ),
        migrations.AddField(
            model_name="word",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="words",
                to="learning.topic",
            ),
        ),
    ]
