# Generated by Django 5.0.2 on 2025-03-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_remove_word_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="words",
                to="learning.topic",
            ),
        ),
    ]
