# Generated by Django 5.0.2 on 2025-03-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_word_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="topic",
        ),
    ]
